# fly.toml app configuration file generated for phonebook-z on 2023-10-21T22:35:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-z"
primary_region = "dfw"

[build]

[env]
  PORT = "3001" 

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
